import type { Metadata } from "next";
import Providers from "../context/provider";
import Header from "@/components/Header/Header";
import NavBar from "@/components/NavBar/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="flex">
            <NavBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
