version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env # This tells Docker to pull variables from your .env file
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER} # Pulls 'postgres' from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Pulls 'postgres' from .env
      POSTGRES_DB: ${DB_NAME} # Pulls 'DevSphere' from .env
    ports:
      - '5433:5432' # Changed local port to 5433 to avoid conflict with your existing pgAdmin Postgres
